# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: portr.ctnr.ctl.io/ys-cpc/gcp-bq-reporting
  tag: 1.0.0-DEV
  pullPolicy: Always

service:
  name: gcp-bq-reporting
  type: ClusterIP
  externalPort: 30000
  internalPort: 30000

resources:
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 0.5
    memory: 500Mi

secret:
  portr:
    name: portr
    enabled: false

location: ca3
