{{- if .Values.secret.portr.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.secret.portr.name }}
  labels:
    name: {{ .Values.secret.portr.name }}
data:
  .dockerconfigjson: {{ .Values.secret.portr.auth }}
type: kubernetes.io/dockerconfigjson
{{- end }}